import App from "./App";
import AppSessionProvider from "./core/auth/AppSessionProvider";
import Script from "next/script";
import { SideBar, NavBar, Footer } from "@core/ui/layout/components";
import { UIToast } from '@core/infrastructure/ui/components';
import  "./globals.css";

//theme
import "primereact/resources/themes/bootstrap4-light-blue/theme.css";
//core
import "primereact/resources/primereact.min.css";
//icons
import "primeicons/primeicons.css";

/*
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};*/

interface RootLayoutProps {
  children: React.ReactNode
}

export default function RootLayout({ children }: RootLayoutProps) {

  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>Smart Green</title>
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
          rel="stylesheet"
        />
        <link href="https://fonts.googleapis.com/css2?family=Poppins" rel="stylesheet" />
        <link href="/css/app.css" rel="stylesheet" />
        <link href="/css/custom.css" rel="stylesheet" />
        <link rel="shortcut icon" href="#"></link>
      </head>
      <body className="container-fluid">

        <AppSessionProvider>
          <UIToast />
          <App>
            <div className="bg-light.bg-gradient">
              <div className="">
                {/* <NavBar />               */}
                <SideBar />
                <main id="main-targets" className=" px-4 pt-2 close">
                  {children}
                </main>

                {false &&
                  <Footer />
                }
              </div>
            </div>
            <Script
              src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
              id="bootstrap"
            />
            <Script src="/js/modules/sidebar.js" id="sidebar" />
            <Script src="/js/modules/utils.js" id="sidebar2" />

          </App>
        </AppSessionProvider>
      </body>
    </html>
  );
}


